FROM elixir:1.6-otp-21

ENV DEBIAN_FRONTEND=noninteractive
ENV HOME=/opt/app/ TERM=xterm
ENV MIX_ENV=prod REPLACE_OS_VARS=true

# Install Hex+Rebar
RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /opt/app

# Cache elixir deps
COPY mix.exs mix.lock ./
RUN mix deps.get

COPY config ./config
RUN mix deps.compile

COPY . .

RUN mix release --env=prod